# Generated by Django 5.1.3 on 2024-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_description_alter_job_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.CharField(default='Default Job Description', max_length=1000),
        ),
    ]
